name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: digitalboyzone/mathgpt_frontend_admin:latest

      - name: Deploy Docker image and update Nginx configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 停止并删除旧的容器
            docker stop mathgpt_frontend_admin || true
            docker rm mathgpt_frontend_admin || true

            # 拉取最新的镜像并运行新的容器
            docker pull digitalboyzone/mathgpt_frontend_admin:latest  
            docker run -d -p 9000:80 -p 9001:3001 --name mathgpt_frontend_admin --restart always digitalboyzone/mathgpt_frontend_admin:latest
